# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: RPNOW
tagline: 'All About Films'
description: 'RP Now is Youtube Channel all Videos are available here and Film Reveiws, Public Talk and So on.'
keywords: 'film, sandalwood, Film talk, Youtube videos, entertainment news'
url: https://rpnow.in
baseurl: 
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: RP Now
  bio: RP Now is Youtube Channel Film Videos are available here.
  image: author
  url: https://rpnow.in
  email: hello@connorbaer.co
  twitter: connor_baer

social:
  twitter: https://twitter.com/connor_baer
  instagram: https://instagram.com/connor_baer
  github: https://github.com/connor-baer/summer

version: 2.0.0

github:
  repo: https://github.com/connor-baer/summer

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  News: https://rpnow.in/news
  Youtube: https://www.youtube.com/channel/UCJ2y_IXqvBGzDfMaLm7t3Kw

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
